#!/system/bin/sh

export PATH=$PATH:/system/xbin:/sbin:/vendor/bin:/system/sbin:/system/bin
if [ -d "/data/local/busybox*/xbin" ]; then
	export PATH=$PATH:`ls -d /data/local/busybox*/xbin 2>/dev/null`;
fi

LOG=/data/local/02misctweaks.log;

if [ -e $LOG ]; then
	rm $LOG;
fi;

touch $LOG;
echo "# LOGGING ENGINE" > $LOG;
##Re-Mount /system, /data and /cache for better performance
sync

# --------------------------------------- #
# | Remount with noatime and nodiratime | #
# --------------------------------------- #
for k in $(busybox mount | cut -d " " -f3); do
	busybox sync;
	busybox mount -o remount,noatime,noauto_da_alloc,barrier=0,data=writeback,nobh $k 2>/dev/null;
done;

 for i in \
	`busybox find /data -iname "*.db"`; 
 do \
	sqlite3 $i 'VACUUM;'; 
	sqlite3 $i 'REINDEX;'; 
 done
	
#Clear logs
rm -f /data/log/*

sync;

echo "" >> $LOG;
echo "$( date +"%m-%d-%Y %H:%M:%S" ) miscellaneous tweaks applied..." >> $LOG;

exit 0